version: "3"

services:
  vote:
    build: ./vote
    image: kushalsrihari/vote
    command: python app.py
    volumes:
     - ./vote:/app
    ports:
      - "4000:80"

  redis:
    image: redis:alpine
    ports: ["6379"]

  worker:
    build: ./worker
    image: kushalsrihari/worker

  db:
    image: postgres:9.4
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"

  result:
    build: ./result
    image: kushalsrihari/result
    command: nodemon server.js
    volumes:
      - ./result:/app
    ports:
      - "4001:80"
      - "5858:5858"
